# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'front'
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'front/package-lock.json'
        
    - run: npm install
      working-directory: 'front'
      
    - name: Run Karma Tests with Coverage
      run: npm run test -- --code-coverage --no-watch --source-map=false --browsers=ChromeHeadless
      working-directory: 'front'

    - name: Run SonarQube analysis
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner -Dsonar.projectKey=G-Wald_BobApp_front -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.exclusions=**/node_modules/** -Dsonar.tests=src -Dsonar.test.inclusions=**/*.spec.ts -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info 

      
  docker-image-publish:
    needs: build-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build  Docker image
      run: docker build -t waldh69/bobapp-project:bobapp-front -f front/Dockerfile .
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Publish Docker image
      run: docker push waldh69/bobapp-project:bobapp-front
